### PR TITLE
Handle pretty and base <> collision

### PR DESCRIPTION
**Pull request by AndreasLoow**
Because `<>` was added to Prelude in base 4.11.0.0 one gets the following error when trying to build BNFC with e.g. GHC 8.4.1:

```
[10 of 97] Compiling BNFC.PrettyPrint ( src/BNFC/PrettyPrint.hs, dist/build/bnfc/bnfc-tmp/BNFC/PrettyPrint.o )

src/BNFC/PrettyPrint.hs:16:13: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at src/BNFC/PrettyPrint.hs:2:8-23
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.<>’,
                             imported from ‘Text.PrettyPrint’ at src/BNFC/PrettyPrint.hs:10:1-23
                             (and originally defined in ‘Text.PrettyPrint.HughesPJ’)
   |
16 | a <.> b = a <> "." <> b
   |             ^^

src/BNFC/PrettyPrint.hs:16:20: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at src/BNFC/PrettyPrint.hs:2:8-23
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.<>’,
                             imported from ‘Text.PrettyPrint’ at src/BNFC/PrettyPrint.hs:10:1-23
                             (and originally defined in ‘Text.PrettyPrint.HughesPJ’)
   |
16 | a <.> b = a <> "." <> b
   |                    ^^
```

I'm not sure about the proper way of fixing this, but this PR at least builds on GHC 8.4.1. See also haskell/pretty#30.

### CODE REVIEW

**Comment by AndreasLoow** [comment]
(Someone might want to add 8.4 to `.travis.yml` also.)

**Comment by andreasabel** [comment]
Mmh, after pulling your patches, the small test suites fail. (See travis output.)

**Comment by AndreasLoow** [comment]
LOL, :(. Enabling CPP removes `/* these comments */` (but not `// these comments`) from the test specs. I'm not sure how to solve it, will try to think of something.

**Comment by AndreasLoow** [comment]
Hmmmmmmm, the new attempt doesn't work either, because of this: https://www.reddit.com/r/haskell/comments/3ryf2p/how_can_you_use_a_custom_prelude_with_ghci/. (The doctests dies when starting GHCI.)

**Comment by AndreasLoow** [comment]
The third attempt seems to work!

**Comment by SantiMunin** [comment]
Is this change available in Hackage? I'm hitting this error (using 8.4.2).

**Comment by AndreasLoow** [comment]
No it's not (the latest Hackage release seems to be from 2016), as a temporary workaround you can install BNFC from the Git repo instead.

**Comment by SantiMunin** [comment]
Yep.

I just used ghc-8.2.2 to install it. Thanks
