### ISSUE TITLE
BNFC-2.8 does not compile with alex 3.1.5

### ISSUE THREAD

**Issue by peti** [BNFC/bnfc#162]
Citing from http://hydra.cryp.to/build/1392291/nixlog/1/raw:

~~~~
src/LexBNF.x:164:38:
    Not in scope: ‘ord’
    Perhaps you meant one of these:
      ‘or’ (imported from Prelude), ‘odd’ (imported from Prelude),
      ‘ord#’ (imported from GHC.Exts)
~~~~

**Comment by johnjcamilleri** [comment]
I put a solution to this in #161 if you just need a quick local fix (untested with other versions)

**Comment by peti** [comment]
Unfortunately, I need a fix available on Hackage. I'm maintaining the BNFC package for NixOS.

**Comment by gdetrez** [comment]
I pushed a new version on hackage that addresses this problem, @peti can you try and confirm that it works?

**Comment by peti** [comment]
Yes, the new version compiles correctly with alex 3.1.7. Thank you!

**Comment by rybak** [comment]
@gdetrez can you specify the version of bnfc in which the issue got fixed?
