### ISSUE TITLE
`bnfc-system-tests` does not build with `HTF-0.15`

### ISSUE THREAD

**Issue by andreasabel** [BNFC/bnfc#416]
`bnfc-system-tests` does not build with `HTF-0.15`:
```
src/TestUtils.hs:27:24: error:
    Module ‘Test.Framework’ does not export ‘assertEqualPretty_’
   |
27 | import Test.Framework (assertEqualPretty_, assertEqual_)
   |                        ^^^^^^^^^^^^^^^^^^

src/TestUtils.hs:27:44: error:
    Module ‘Test.Framework’ does not export ‘assertEqual_’
   |
27 | import Test.Framework (assertEqualPretty_, assertEqual_)
   |                                            ^^^^^^^^^^^^
```
