### ISSUE TITLE
installation script 'cabal install alex happy BNFC' fails on Mac

### ISSUE THREAD

**Issue by marcbezem** [BNFC/bnfc#236]
...
Configuring BNFC-2.8.1...
Building BNFC-2.8.1...
Building alex-3.2.4...
Configuring Cabal-2.4.0.1...
Building Cabal-2.4.0.1...
Failed to install BNFC-2.8.1
Build log ( /Users/bezem/.cabal/logs/ghc-8.4.3/BNFC-2.8.1-9jjtOb6e6BK7NOBMrYhG4b.log ):
cabal: Entering directory '/var/folders/gk/y97zlzbs4zg4vr7p0rs03z7r0000gp/T/cabal-tmp-25244/BNFC-2.8.1'
Configuring BNFC-2.8.1...
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
Preprocessing executable 'bnfc' for BNFC-2.8.1..
Building executable 'bnfc' for BNFC-2.8.1..
[ 1 of 97] Compiling AbsBNF           ( src/AbsBNF.hs, dist/build/bnfc/bnfc-tmp/AbsBNF.o )
[ 2 of 97] Compiling BNFC.Backend.CPP.NoSTL.RegToFlex ( src/BNFC/Backend/CPP/NoSTL/RegToFlex.hs, dist/build/bnfc/bnfc-tmp/BNFC/Backend/CPP/NoSTL/RegToFlex.o )
[ 3 of 97] Compiling BNFC.Backend.CPP.STL.STLUtils ( src/BNFC/Backend/CPP/STL/STLUtils.hs, dist/build/bnfc/bnfc-tmp/BNFC/Backend/CPP/STL/STLUtils.o )
[ 4 of 97] Compiling BNFC.Backend.CSharp.RegToGPLEX ( src/BNFC/Backend/CSharp/RegToGPLEX.hs, dist/build/bnfc/bnfc-tmp/BNFC/Backend/CSharp/RegToGPLEX.o )
[ 5 of 97] Compiling BNFC.Backend.Common.StrUtils ( src/BNFC/Backend/Common/StrUtils.hs, dist/build/bnfc/bnfc-tmp/BNFC/Backend/Common/StrUtils.o )
[ 6 of 97] Compiling BNFC.Backend.Haskell.MkErrM ( src/BNFC/Backend/Haskell/MkErrM.hs, dist/build/bnfc/bnfc-tmp/BNFC/Backend/Haskell/MkErrM.o )
[ 7 of 97] Compiling BNFC.Backend.Haskell.MkSharedString ( src/BNFC/Backend/Haskell/MkSharedString.hs, dist/build/bnfc/bnfc-tmp/BNFC/Backend/Haskell/MkSharedString.o )
[ 8 of 97] Compiling BNFC.Backend.Haskell.RegToAlex ( src/BNFC/Backend/Haskell/RegToAlex.hs, dist/build/bnfc/bnfc-tmp/BNFC/Backend/Haskell/RegToAlex.o )
[ 9 of 97] Compiling BNFC.Backend.Java.RegToJLex ( src/BNFC/Backend/Java/RegToJLex.hs, dist/build/bnfc/bnfc-tmp/BNFC/Backend/Java/RegToJLex.o )
[10 of 97] Compiling BNFC.PrettyPrint ( src/BNFC/PrettyPrint.hs, dist/build/bnfc/bnfc-tmp/BNFC/PrettyPrint.o )

src/BNFC/PrettyPrint.hs:16:13: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at src/BNFC/PrettyPrint.hs:2:8-23
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.<>’,
                             imported from ‘Text.PrettyPrint’ at src/BNFC/PrettyPrint.hs:10:1-23
                             (and originally defined in ‘Text.PrettyPrint.HughesPJ’)
   |
16 | a <.> b = a <> "." <> b
   |             ^^

src/BNFC/PrettyPrint.hs:16:20: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at src/BNFC/PrettyPrint.hs:2:8-23
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.<>’,
                             imported from ‘Text.PrettyPrint’ at src/BNFC/PrettyPrint.hs:10:1-23
                             (and originally defined in ‘Text.PrettyPrint.HughesPJ’)
   |
16 | a <.> b = a <> "." <> b
   |                    ^^
cabal: Leaving directory '/var/folders/gk/y97zlzbs4zg4vr7p0rs03z7r0000gp/T/cabal-tmp-25244/BNFC-2.8.1'
Installed alex-3.2.4

Installed Cabal-2.4.0.1
Updating documentation index
/Users/bezem/Library/Haskell/share/doc/x86_64-osx-ghc-8.4.3/index.html
cabal: Error: some packages failed to install:
BNFC-2.8.1-9jjtOb6e6BK7NOBMrYhG4b failed during the building phase. The
exception was:
ExitFailure 1

**Comment by brokenpylons** [comment]
Same problem on Arch Linux. Installing from git works, though...

**Comment by AndreasLoow** [comment]
Yeah, thank you. This is known and will be resolved by #234.

**Comment by andreasabel** [comment]
BNFC 2.8.2 will work with ghc 8.4.4 (keeping fingers crossed).
